shop/Models/dienThoai.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace shop.Models
{
    public class dienThoai
    {
        public int id { get; set; }
        public string name { get; set; }
        public int price { get; set; }
        public string category { get; set; }
        public string urlImage { get; set; }

    }
}

shop/Models/donHang.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace shop.Models
{
    public class donHang
    {
        public int ID { get; set; }
        public string TenKhachHang { get; set; }
        public string SoDienThoai { get; set; }
        public string DiaChiGiaoHang { get; set; }
        public DateTime NgayDatHang { get; set; }
        public List<dienThoai> DienThoaiDatMua = new List<dienThoai>();
    }
}

shop/Models/dsDienThoai.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace shop.Models
{
    public static class dsDienThoai
    {
        public static List<dienThoai> danhsach = new List<dienThoai>();
    }
}

shop/Models/dsDonHang.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace shop.Models
{
    public static class dsDonHang
    {
        public static List<donHang> danhsachDonHang = new List<donHang>();
    }
}

shop/Controllers/DonHangController.cs
using shop.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace shop.Controllers
{
    public class DonHangController : Controller
    {
        // GET: DonHang
        public ActionResult Index()
        {
            return View(dsDonHang.danhsachDonHang);
        }
        public ActionResult create()
        {
            return View(new donHang());
        }
        [HttpPost]
        public ActionResult create(donHang dh)
        {
            dsDonHang.danhsachDonHang.Add(dh);
            return RedirectToAction("index");
        }
        public ActionResult edit(int id_DonHang)
        {
            var ds = dsDonHang.danhsachDonHang.SingleOrDefault(m => m.ID == id_DonHang);
            return View(ds);
        }
        [HttpPost]
        public ActionResult edit(donHang dh)
        {
            var dsdt = dsDonHang.danhsachDonHang.SingleOrDefault(m => m.ID == dh.ID);
            dsdt.TenKhachHang = dh.TenKhachHang;
            dsdt.DiaChiGiaoHang = dh.DiaChiGiaoHang;
            dsdt.SoDienThoai = dh.SoDienThoai;
            dsdt.NgayDatHang = dh.NgayDatHang;
            return RedirectToAction("index");
        }
        public ActionResult delete(int id_DonHang)
        {
            var ds = dsDonHang.danhsachDonHang.SingleOrDefault(m => m.ID == id_DonHang);
            dsDonHang.danhsachDonHang.Remove(ds);
            return RedirectToAction("index");
        }
        public ActionResult chi_tiet(int id_DonHang)
        {
            var ds = dsDonHang.danhsachDonHang.SingleOrDefault(m => m.ID == id_DonHang);
            return View(ds);
        }
        public ActionResult them_chi_tiet(int id_DonHang)
        {
            ViewBag.id_DonHang = id_DonHang;
            return View(new dienThoai());
        }
        [HttpPost]
        public ActionResult them_chi_tiet(dienThoai dt, HttpPostedFileBase fileAnh)
        {
            var ds = dsDonHang.danhsachDonHang.SingleOrDefault(m => m.ID == dt.id);

            if (fileAnh != null)
            {
                string rootFolder = Server.MapPath("/Data/");
                string pathAnh = rootFolder + "/" + fileAnh.FileName;
                fileAnh.SaveAs(pathAnh);
                dt.urlImage = "/Data/" + fileAnh.FileName;
            }
            else
            {
                dt.urlImage = "null";
            }
            ds.DienThoaiDatMua.Add(dt);
            return RedirectToAction("chi_tiet", new {id_DonHang = dt.id});
        }
    }
}

shop/Views/DonHang/Index.cshtml
@model IEnumerable<shop.Models.donHang>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutHome.cshtml";
}

<p>Danh sách đơn hàng</p>
<p>
    @Html.ActionLink("Thêm mới", "create")
</p>
<table class="table">
    <tr>
        <th>ID</th>
        <th> Tên khách hàng </th>
        <th> Số điện thoại </th>
        <th> Địa chỉ giao hàng </th>
        <th> Ngày đặt hàng </th>
        <th> Chức năng </th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TenKhachHang)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SoDienThoai)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DiaChiGiaoHang)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NgayDatHang)
            </td>
            <td>
                <a href="~/DonHang/edit?id_DonHang=@item.ID">Sửa</a> |
                <a href="~/DonHang/chi_tiet?id_DonHang=@item.ID">Chi tiết</a>  |
                <a onclick="xoa()" href="~/DonHang/delete?id_DonHang=@item.ID">Xoá</a>
            </td>
        </tr>
    }

</table>
@section script{
    <script>
        function xoa() {
            var x = confirm("Bạn muốn xoá?");
            if (x)
                return true;
            else
                return false;
        }
    </script>
}

shop/Views/DonHang/Search.cshtml
@model IEnumerable<shop.Models.donHang>

@{
    ViewBag.Title = "Search";
    Layout = "~/Views/Shared/_LayoutHome.cshtml";
}

<h2>Search</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TenKhachHang)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SoDienThoai)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DiaChiGiaoHang)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NgayDatHang)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.TenKhachHang)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SoDienThoai)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DiaChiGiaoHang)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NgayDatHang)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

shop/Views/DonHang/chi_tiet.cshtml
@model shop.Models.donHang

@{
    ViewBag.Title = "Chi tiết";
    Layout = "~/Views/Shared/_LayoutHome.cshtml";
}

<div>
    <p>Chi tiết đơn hàng</p>
    <hr />
    <div class="row">
        <div class="col-lg-4">
            <dl class="dl-horizontal">
                <dt> Tên khách hàng</dt>
                <dd> @Html.DisplayFor(model => model.TenKhachHang) </dd>

                <dt> Số điện thoại</dt>
                <dd> @Html.DisplayFor(model => model.SoDienThoai) </dd>

                <dt> Địa chỉ giao hàng</dt>
                <dd> @Html.DisplayFor(model => model.DiaChiGiaoHang)</dd>

                <dt> Ngày đặt hàng</dt>
                <dd> @Html.DisplayFor(model => model.NgayDatHang)</dd>
            </dl>
            <p>
               <a href="~/DonHang/edit?id_DonHang=@Model.ID">Chỉnh sửa</a>|
                @Html.ActionLink("Trở về trang trước", "Index","DonHang")
            </p>
        </div>
        <div class="col-lg-8">
            <a href="~/DonHang/them_chi_tiet?id_DonHang=@Model.ID">Thêm chi tiết</a>
            <table class="table">
                <tr>
                    <th>Id: </th>
                    <th>Tên: </th>
                    <th>Giá: </th>
                    <th>Loại: </th>
                    <th>Hình ảnh: </th>
                </tr>

                @foreach (var item in Model.DienThoaiDatMua)
                {
                    <tr>
                        <td>@item.id</td>
                        <td>@item.name</td>
                        <td>@item.price</td>
                        <td>@item.category</td>
                        <td><img src="@item.urlImage" width="50px" height="50px"/></td>
                    </tr>
                }
            </table>
        </div>
    </div>
</div>

shop/Views/DonHang/create.cshtml
@model shop.Models.donHang

@{
    ViewBag.Title = "Thêm mới";
    Layout = "~/Views/Shared/_LayoutHome.cshtml";
}
@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal container">
    <p>Thêm đơn hàng mới</p>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        <p>ID</p>
        <div class="col-md-10">
            @Html.EditorFor(model => model.ID, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>

    <div class="form-group">
        <p>Tên khách hàng</p>
        <div class="col-md-10">
            @Html.EditorFor(model => model.TenKhachHang, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>

    <div class="form-group">
        <p>Số điện thoại</p>
        <div class="col-md-10">
            @Html.EditorFor(model => model.SoDienThoai, new { htmlAttributes = new { @class = "form-control",@type="number" } })
        </div>
    </div>

    <div class="form-group">
        <p>Địa chỉ giao hàng</p>
        <div class="col-md-10">
            @Html.EditorFor(model => model.DiaChiGiaoHang, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>

    <div class="form-group">
        <p>Ngày đặt hàng</p>
        <div class="col-md-10">
            @{ 
                var dates = Html.Raw(DateTime.Now.ToString("yyyy-MM-dd HH:mm").Replace(' ', 'T'));
            }
            <input name="NgayDatHang" value="@dates" type="datetime-local" class="form-control"/>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Thêm" class="btn btn-default bg-success" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Trở về trang trước", "Index","DonHang")
</div>

shop/Views/DonHang/edit.cshtml
@model shop.Models.donHang

@{
    ViewBag.Title = "edit";
    Layout = "~/Views/Shared/_LayoutHome.cshtml";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Sửa đơn hàng</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            <p>Tên khách hàng</p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenKhachHang, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenKhachHang, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <p>Số điện thoại</p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoDienThoai, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SoDienThoai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <p>Địa chỉ giao hàng</p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.DiaChiGiaoHang, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DiaChiGiaoHang, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <p>Ngày đặt hàng</p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgayDatHang, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgayDatHang, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

shop/Views/DonHang/them_chi_tiet.cshtml
@model shop.Models.dienThoai

@{
    ViewBag.Title = "them_chi_tiet";
    Layout = "~/Views/Shared/_LayoutHome.cshtml";
}


@using (Html.BeginForm("Them_chi_tiet", "DonHang", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Thêm sản phẩm</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <input value="@ViewBag.id_DonHang" type="hidden"/>
        <div class="form-group">
            <p>Tên sản phẩm</p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <p>Giá sản phẩm</p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <p>Loại sản phẩm</p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.category, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.category, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <p>Hình ảnh</p>
            <div class="col-md-10">
                <input type="file" class="form-control" name="fileAnh" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

shop/Views/Shared/_LayoutHome.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>@ViewBag.Title</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel="stylesheet" href="~/Content/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/Content/css/style.css">
    <script src="~/Content/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="~/Content/font/css/font-awesome.min.css">
</head>
<body>

    <!-- navar1 -->
    <section>
        <div class="row" style="background-color: rgb(217, 224, 243);">
            <div class="col-lg-2" style="height: 40px; padding-top: 6px; text-align: center;">
                <a class="text-dark px-2" href=""><i class="fa fa-facebook"></i></a>
                <a class="text-dark px-2" href=""><i class="fa fa-github"></i></a>
                <a class="text-dark px-2" href=""><i class="fa fa-envelope"></i></a>
                <a class="text-dark px-2" href=""><i class="fa fa-instagram"></i></a>
            </div>
            <div class="col-lg-8" style="text-align: center;">
                <input class="navar-input" placeholder="Tìm kiếm">
                <a><i class="fa fa-search" style="font-size: 18px; color: #df8da2;"></i></a>
            </div>
            <div class="col-lg-2 navar-cart">
                <div class="navar-button">
                    <a href="" class="text-dark">
                        <i class="fa fa-shopping-cart" aria-hidden="true"
                           style="color: #df8da2;"></i>
                    </a>
                    <span class="navar-font">0</span>
                </div>
                <div class="navar-button">
                    <a><i class="fa fa-user-circle-o" aria-hidden="true" style="color: #df8da2;"></i></a>
                </div>
            </div>
        </div>
    </section>
    <!-- navar2 -->
    <section>
        <div class="row">
            <ul id="nav">
                <li id="nav-1"><img src="~/Content/css/logo.svg" alt="logo" height="105%"></li>
                <li id="nav-2"><a href="http://www.free-css.com/" class="nav-a">Trang chủ</a></li>
                <li id="nav-3"><a href="http://www.free-css.com/" class="nav-a">Sản phẩm</a></li>
                <li>
                    <div class="dropdown">
                        <button class="dropbtn"><i class="fa fa-bars" aria-hidden="true"></i></button>
                        <div class="dropdown-content">
                            <a href="~/Views/Home/TrangChu.cshtml">Trang chủ</a>
                            <a href="~/Views/Home/sanPham.cshtml">Sản phẩm</a>
                            <a href="#">Thông tin</a>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
        @*<span>@ViewBag.Title</span>*@
    </section>
    <section>
        <div class="container bodys" style="min-height:500px">
            @RenderBody()

        </div>
        @*@{ 
            List<string> ds = (List<string>)ViewBag.Danhsach;
            for(int i= 0; i < ds.Count; i++)
            {
                <span>@ds[i]</span>
            }
        }*@
    </section>
    <!-- -------------------------------Chân trang -->
    <section>
        <div class="fots">
            <div class="row">
                <div class="col-lg-3">
                    <div class="container">
                        <p style="text-align: center;"><img src="~/Content/css/logo.svg" alt="logo" height="105%"></p>
                        <p style="text-align: justify; font-size: 18px;">
                            &nbsp;&nbsp;<b>Shop Chú Lùn</b> chuyên bán quần, áo, sản phẩm giày dép phù hợp với con em bạn,
                            chúng tôi nhập sản phẩm ở những hãng mai uy tín và chất lượng.
                        </p>
                        <p><i class="fa fa-map-marker" aria-hidden="true"></i> Hiếu Tử -Tiểu Cần -Trà Vinh</p>
                        <p><i class="fa fa-envelope" aria-hidden="true"></i> nhutnhut.pip@gmail.com</p>
                        <p><i class="fa fa-phone-square" aria-hidden="true"></i> 012345678</p>
                    </div>
                </div>
                <div class="col-lg-3">

                </div>
                <div class="col-lg-3">
                </div>
            </div>
            <p style="text-align: center;">Bảng quyền thuộc &reg; <a href="https://github.com/nhut-py/">nhut-py</a></p>
        </div>
        <a href="#" class=" back-to-top" style="display: inline; text-align: center;">
            <i class="fa fa-angle-double-up" style="font-weight: bold; font-size: 35px;"></i>
        </a>
    </section>
    @RenderSection("script",false)
</body>
</html>

shop/Views/Shared/_PartialHeader.cshtml
<section>
    <a href="#" class=" back-to-top" style="display: inline; text-align: center;">
        <i class="fa fa-angle-double-up" style="font-weight: bold; font-size: 35px;"></i>
    </a>
    <div class="fixed-bottom fot">
        <div class="row">
            <div class="col-lg-3">
                <div class="container">
                    <p style="text-align: center;"><img src="~/Content/css/logo.svg" alt="logo" height="105%"></p>
                    <p style="text-align: justify; font-size: 18px;">
                        &nbsp;&nbsp;<b>Shop Chú Lùn</b> chuyên bán quần, áo, sản phẩm giày dép phù hợp với con em bạn,
                        chúng tôi nhập sản phẩm ở những hãng mai uy tín và chất lượng.
                    </p>
                    <p><i class="fa fa-map-marker" aria-hidden="true"></i> Hiếu Tử -Tiểu Cần -Trà Vinh</p>
                    <p><i class="fa fa-envelope" aria-hidden="true"></i> nhutnhut.pip@gmail.com</p>
                    <p><i class="fa fa-phone-square" aria-hidden="true"></i> 012345678</p>
                </div>
            </div>
            <div class="col-lg-3">

            </div>
            <div class="col-lg-3">
            </div>
        </div>
        <p style="text-align: center;">Bảng quyền thuộc &reg; <a href="https://github.com/nhut-py/">nhut-py</a></p>
    </div>

</section>